### ISSUE TITLE
Issue with geoWithin()

### ISSUE THREAD

**Issue by bsacks99** [michaelmoussa/doctrine-qbmocker#19]
I keep running into this issue: "PHPUnit_Framework_MockObject_RuntimeException: Cannot mock Doctrine\MongoDB\Query\Builder::geoWithin() because a class or interface used in the signature is not loaded". I originally tried just mocking the document manager directly and hit the issue as well. I thought your module might resolve this for me, but I am still getting it. I'm not sure what the issue is other then I am sure I am missing this class.

**Comment by michaelmoussa** [comment]
@bsacks99 Did you install the `jmikola/geojson` Composer package? https://github.com/michaelmoussa/doctrine-qbmocker/blob/master/composer.json#L24

I didn't explicitly require it because some people may only be using this library for ORM, but it's listed in the suggest and in the [readme](https://github.com/michaelmoussa/doctrine-qbmocker#dependencies) for ODM.

Running `composer require jmikola/geojson` should take care of this.

**Comment by bsacks99** [comment]
Thanks for the quick response Michael! I'll install the dependency and update the issue when resolved.

**Comment by michaelmoussa** [comment]
Closing old issue with no further response. Please re-open if this is still an issue.
